name: nn
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2025.9.9=h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=24.2=py38h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.8.20=he870216_0
  - readline=8.3=hc2a1206_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.44.0=py38h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - addict==2.4.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - backcall==0.2.0
      - cachetools==5.5.2
      - certifi==2022.12.7
      - cffi==1.17.1
      - charset-normalizer==2.1.1
      - click==8.1.8
      - cmake==3.25.0
      - colorama==0.4.6
      - comm==0.2.3
      - contourpy==1.1.1
      - crcmod==1.7
      - cryptography==46.0.3
      - cycler==0.12.1
      - debugpy==1.8.17
      - decorator==5.2.1
      - et-xmlfile==2.0.0
      - executing==2.2.1
      - filelock==3.14.0
      - fonttools==4.57.0
      - frozenlist==1.5.0
      - fsspec==2025.3.0
      - ftfy==6.2.3
      - future==1.0.0
      - google-auth==2.42.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.70.0
      - idna==3.4
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - ipykernel==6.29.5
      - ipython==8.12.3
      - jedi==0.19.2
      - jinja2==3.1.6
      - jmespath==0.10.0
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - kiwisolver==1.4.7
      - lightning-utilities==0.11.9
      - lit==15.0.7
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mmcv==2.0.0
      - mmdet==3.3.0
      - mmengine==0.10.7
      - model-index==0.1.11
      - mpmath==1.3.0
      - multidict==6.1.0
      - nest-asyncio==1.6.0
      - networkx==3.0
      - numpy==1.24.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.3.1
      - opencv-python==4.12.0.88
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openpyxl==3.1.5
      - openxlab==0.1.3
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==24.2
      - pandas==2.0.3
      - parso==0.8.5
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.2.0
      - platformdirs==4.3.6
      - prettytable==3.11.0
      - prompt-toolkit==3.0.52
      - propcache==0.2.0
      - protobuf==5.29.5
      - psutil==7.1.2
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycocotools==2.0.7
      - pycparser==2.23
      - pycryptodome==3.23.0
      - pygments==2.19.2
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2023.4
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - regex==2024.11.6
      - requests==2.28.2
      - requests-oauthlib==2.0.0
      - rich==13.4.2
      - rsa==4.9.1
      - scipy==1.10.1
      - seaborn==0.13.2
      - setuptools==60.2.0
      - shapely==2.0.7
      - six==1.17.0
      - stack-data==0.6.3
      - sympy==1.13.3
      - tabulate==0.9.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - termcolor==2.4.0
      - terminaltables==3.1.10
      - tomli==2.3.0
      - torch==2.0.1+cu118
      - torchaudio==2.0.2+cu118
      - torchmetrics==1.5.2
      - torchvision==0.15.2+cu118
      - tornado==6.4.2
      - tqdm==4.65.2
      - traitlets==5.14.3
      - triton==2.0.0
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - urllib3==1.26.13
      - wcwidth==0.2.14
      - werkzeug==3.0.6
      - yapf==0.43.0
      - yarl==1.15.2
      - zipp==3.20.2
prefix: /root/.conda/envs/nn
